const SHOP_DATA = [
    {
      id: 1,
      type: 'red',
      varietal: 'merlot',
      title: 'Josh Merlot',
      description: 'A good budget merlot.',
      imageUrl: '/assets/images/joshmerlot.webp',
      price: 15.99,
      size: '750ml',
      inventoryLocal: 12,
      inventoryAll: 200,
      canDeliver: true,
      shipStates: ['AZ', 'CA', 'NY'],
      inStoreOnly: false,
      bigregion: 'California',
      region: 'Sonoma',
    },
    {
      id: 2,
      type: 'red',
      varietal: 'merlot',
      title: 'Duckhorn Merlot',
      description: 'A classic California merlot.',
      imageUrl: '/assets/images/duckhornmerlot.webp',
      price: 49.99,
      size: '750ml',
      inventoryLocal: 3,
      inventoryAll: 15,
      canDeliver: true,
      shipStates: [],
      inStoreOnly: false,
      bigregion: 'California',
      region: 'Sonoma',
    },
    {
      id: 3,
      brand: 'Radius',
      type: 'red',
      varietal: 'merlot',
      style: 'Fresh',
      abv: '13.5%',
      taste: 'Vanilla, Raspberry',
      body: 'Medium-bodied',
      sku: '109683750-1',
      title: 'Radius Merlot',
      description: 'Washington- Flavors and aromas of sweet cherries, ripe red raspberries, succulent plums and marshmallow-y vanilla leading to a soft and silky finish. Enjoy with red meats, grilled fish and sharp cheeses.',
      imageUrl: '/assets/images/radius-merlot.webp',
      price: 7.99,
      size: '750ml',
      inventoryLocal: 3,
      inventoryAll: 52,
      canDeliver: true,
      shipStates: ['AZ', 'CA', 'NY'],
      inStoreOnly: false,
      bigregion: 'Washington',
      region: 'Horse Heaven Hills',
    },
    {
      id: 4,
      type: 'red',
      varietal: 'merlot',
      title: 'Stags Leap Merlot',
      description: 'A great Califronia merlot.',
      imageUrl: '/assets/images/stags-leap-merlot.webp',
      price: 24,
      size: '750ml',
      inventoryLocal: 15,
      inventoryAll: 145,
      canDeliver: true,
      shipStates: ['AZ', 'CA', 'NY'],
      inStoreOnly: false,
      bigregion: 'California',
      region: 'Napa',
    },
    {
      id: 5,
      type: 'red',
      varietal: 'merlot',
      title: 'Low Hanging Fruit Merlot',
      description: 'A budget merlot in a Magnum bottle.',
      imageUrl: '/assets/images/low-hanging-fruit-merlot.webp',
      price: 9,
      size: '1.5L',
      inventoryLocal: 6,
      inventoryAll: 29,
      canDeliver: true,
      shipStates: ['AZ', 'CA', 'NY'],
      inStoreOnly: false,
      bigregion: 'California',
      region: 'Napa',
    },
    {
      id: 6,
      type: 'red',
      varietal: 'merlot',
      title: 'Bogle Merlot',
      description: 'A basic merlot.',
      imageUrl: '/assets/images/bogle-merlot.webp',
      price: 8,
      size: '750ml',
      inventoryLocal: 24,
      inventoryAll: 458,
      canDeliver: true,
      shipStates: ['AZ', 'CA', 'NY'],
      inStoreOnly: true,
      bigregion: 'California',
      region: 'Napa',
    },
    {
      id: 7,
      type: 'red',
      varietal: 'pinot-noir',
      title: 'Oregon Pinot Noir',
      description: 'A great Oregon Pinot Noir',
      imageUrl: '/assets/images/oregon-pinot-noir.webp',
      price: 55,
      size: '750ml',
      inventoryLocal: 15,
      inventoryAll: 205,
      canDeliver: true,
      shipStates: ['AZ', 'CA', 'NY'],
      inStoreOnly: false,
      bigregion: 'Oregon',
      region: 'Dundee',
    },
    {
      id: 8,
      type: 'red',
      varietal: 'pinot-noir',
      title: 'California Pinot Noir',
      description: 'A great Calif. pinot noir',
      imageUrl: '/assets/images/california-pinot-noir.webp',
      price: 25,
      size: '750ml',
      inventoryLocal: 8,
      inventoryAll: 93,
      canDeliver: true,
      shipStates: ['AZ', 'CA', 'NY'],
      inStoreOnly: false,
      bigregion: 'California',
      region: 'Napa',
    },
    {
      id: 9,
      type: 'red',
      varietal: 'merlot',
      title: 'Oregon Merlot',
      description: 'A basic merlot.',
      imageUrl: '/assets/images/bogle-merlot.webp',
      price: 12,
      size: '750ml',
      inventoryLocal: 24,
      inventoryAll: 458,
      canDeliver: true,
      shipStates: ['AZ', 'CA', 'NY'],
      inStoreOnly: true,
      bigregion: 'Oregon',
      region: 'Dundee',
    },
];
  
export const WINE_NAMES = [
  {
    merlot: "Merlot",
    cabernetsauvignon: "Cabernet Sauvignon",
    pinotnoir: "Pinot Noir",
    bordeaux: "Bordeaux Blends",
    zinfandel: "Zinfandel",
    chardonnay: "Chardonnay",
    sauvignonblanc: "Sauvignon Blanc",
    riesling: "Riesling",
  }
];

export default SHOP_DATA;